version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "installing something"
      - pnpm install
  pre_build:
    commands:
      - echo "we are in the pre build phase"
      - pnpm run lint
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - pnpm run build
